export const CY_INPUT = '[data-cy="input"]'
export const CY_SUBMIT_BTN = '[data-cy="submit"]'
export const CY_FORM = '[data-cy="form"]'
export const CIRCLES = 'div[class^="circle_circle"]'
export const CY_CLEAR_BTN = '[data-cy="clear"]'
export const CY_REMOVE_BTN = '[data-cy="remove"]'
export const CY_CIRCLE_HEAD = 'div[class*="circle_head"]'
export const CY_CIRCLE_TAIL = 'div[class*="circle_tail"]'

export const CY_LIST_INPUT = '[data-cy="listInput"]'
export const CY_LIST_INDEX_INPUT = '[data-cy="listIndexInput"]'
export const CY_HEAD_ADD_BTN = '[data-cy="headSubmitBtn"]'
export const CY_TAIL_ADD_BTN = '[data-cy="tailSubmitBtn"]'
export const CY_HEAD_REMOVE_BTN = '[data-cy="headRemoveBtn"]'
export const CY_TAIL_REMOVE_BTN = '[data-cy="tailRemoveBtn"]'
export const CY_INDEX_ADD_BTN = '[data-cy="indexAddBtn"]'
export const CY_INDEX_REMOVE_BTN = '[data-cy="indexRemoveBtn"]'