export const cyInput = '[data-cy="input"]'
export const cySubmitBtn = '[data-cy="submit"]'
export const cyForm = '[data-cy="form"]'
export const circles = 'div[class^="circle_circle"]'
export const cyClearBtn = '[data-cy="clear"]'
export const cyRemoveBtn = '[data-cy="remove"]'
export const cyCircleHead = 'div[class*="circle_head"]'
export const cyCircleTail = 'div[class*="circle_tail"]'